const CONFIG = {
    titleWeb: "Người tôi yêu:3",
    introTitle: 'Gửi Vy yêu dấu=)',
    introDesc: `Xin lỗi nhưng cho đuy mò<33`,
    btnIntro: '^^HiHi^^',
    title: 'CHO ĐUY BABE<33',
    desc: 'Yêu babe nhìu ',
    btnYes: 'Ok lun nò:33',
    btnNo: 'Đéo nha!',
    question: 'Tại sao m lại cho Tao:3',
    btnReply: 'Gửi cho bạn <3',
    reply: 'Thích thì làm:3',
    mess: 'Dạ<33',
    messDesc: 'Tí cho nghen!!.',
    btnAccept: 'Okiiiii lun <3',
}
